# Generated by Django 5.2.10 on 2026-01-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Долгота')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='Часовой пояс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало периода')),
                ('date_to', models.DateField(verbose_name='Конец периода')),
                ('min_target_altitude', models.PositiveSmallIntegerField(default=20, help_text='0..90', verbose_name='Мин. высота цели (°)')),
                ('max_cloud_cover', models.PositiveSmallIntegerField(default=40, help_text='0..100', verbose_name='Макс. облачность (%)')),
                ('avoid_moon', models.BooleanField(default=True, verbose_name='Учитывать влияние Луны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='planner.location', verbose_name='Локация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План съёмки',
                'verbose_name_plural': 'Планы съёмки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AstroWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало окна')),
                ('end_time', models.DateTimeField(verbose_name='Конец окна')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Оценка')),
                ('avg_cloud_cover', models.PositiveSmallIntegerField(default=0, verbose_name='Средняя облачность (%)')),
                ('moon_illumination', models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Освещённость Луны (0..1)')),
                ('max_target_altitude', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Макс. высота цели (°)')),
                ('is_astronomical_dark', models.BooleanField(default=False, verbose_name='Астрономическая ночь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astro_windows', to='planner.sessionrequest', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Окно съёмки',
                'verbose_name_plural': 'Окна съёмки',
                'ordering': ['-score', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('target_type', models.CharField(choices=[('Moon', 'Луна'), ('Planet', 'Планета'), ('DSO', 'Deep Sky Object'), ('MilkyWay', 'Млечный путь')], max_length=20, verbose_name='Тип цели')),
                ('right_ascension', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Прямое восхождение (RA, °)')),
                ('declination', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Склонение (Dec, °)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='planner.target', verbose_name='Цель'),
        ),
        migrations.CreateModel(
            name='ForecastHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время (час прогноза)')),
                ('cloud_cover', models.PositiveSmallIntegerField(default=0, verbose_name='Облачность (%)')),
                ('precipitation', models.DecimalField(decimal_places=2, default=0, help_text='Единицы зависят от API (обычно мм)', max_digits=6, verbose_name='Осадки')),
                ('visibility', models.PositiveIntegerField(default=0, help_text='Единицы зависят от API (обычно метры)', verbose_name='Видимость')),
                ('source', models.CharField(default='open-meteo', max_length=64, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_hours', to='planner.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Почасовой прогноз',
                'verbose_name_plural': 'Почасовые прогнозы',
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('location', 'timestamp'), name='uniq_forecast_location_timestamp')],
            },
        ),
    ]
