# Generated by Django 5.2.10 on 2026-01-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanHourScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('score', models.FloatField()),
                ('cloud_cover', models.IntegerField()),
                ('moon_illumination', models.FloatField()),
                ('target_altitude', models.FloatField()),
                ('is_astronomical_dark', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_scores', to='planner.sessionrequest')),
            ],
            options={
                'ordering': ['timestamp'],
                'unique_together': {('plan', 'timestamp')},
            },
        ),
    ]
